langDict = {
    "ar_SA": {
        "Welcome": "أهلاً وسهلاً",
        "Mail": "بريد",
        "Install programs": "تثبيت البرامج",
        "Background": "خلفية",
        "Finish": "إنهاء",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "مرحبًا بك في ServOS. لمتابعة التثبيت،<br>يرجى النقر على \"التالي\"",
        "Cancel": "إلغاء",
        "Next": "التالي",
        "Exit": "خروج",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "إذا كنت تريد إضافة بريدك الإلكتروني إلى عميل البريد،<br>يرجى النقر على \"إضافة بريد إلكتروني\"",
        "Back": "رجوع",
        "Add email": "إضافة بريد إلكتروني",
        "What's programs, which you want to install?": "ما البرامج التي تريد تثبيتها؟",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "لقد أكملت تثبيت ServOS.<br>يمكنك النقر على \"خروج\"",
        "Please to add you community region:": "يرجى إضافة منطقتك:",
        "Please to choose your backgroud:": "يرجى اختيار الخلفية:",
        "Weather": "الطقس",
        "Add": "إضافة",
        "Remove": "إزالة",
        "Your community": "مجتمعك",
        "Time Zone":"المنطقة الزمنية",
        "Please to select your timezone:":"يرجى اختيار منطقتك الزمنية:",
        "Choosing an User Icon":"اختيار أيقونة المستخدم",
        "Please to choose your User Icon:":"يرجى اختيار أيقونة المستخدم:"
    },
    "hy_AM": {
        "Welcome": "Բարի գալուստ",
        "Mail": "Փոստ",
        "Install programs": "Տեղադրել ծրագրեր",
        "Background": "Հետին պլան",
        "Finish": "Ավարտել",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Բարի գալուստ ServOS։ Շարունակելու համար,<br>խնդրում ենք սեղմել «Հաջորդը»",
        "Cancel": "Չեղարկել",
        "Next": "Հաջորդը",
        "Exit": "Ելք",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Եթե ցանկանում եք ավելացնել ձեր էլ․ փոստի հասցեն փոստային հաճախորդին,<br>խնդրում ենք սեղմել «Ավելացնել էլ․ փոստ»",
        "Back": "Հետ",
        "Add email": "Ավելացնել էլ․ փոստ",
        "What's programs, which you want to install?": "Որ ծրագրերը ցանկանում եք տեղադրել?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Դուք ավարտել եք ServOS-ի տեղադրումը։<br>Դուք կարող եք սեղմել «Ելք»",
        "Please to add you community region:": "Խնդրում ենք ավելացնել ձեր համայնքի շրջանը:",
        "Please to choose your backgroud:": "Խնդրում ենք ընտրել ձեր հետին պլանը:",
        "Weather": "Եղանակ",
        "Add": "Ավելացնել",
        "Remove": "Հեռացնել",
        "Your community": "Ձեր համայնքը",
        "Time Zone":"Ժամային գոտի",
        "Please to select your timezone:":"Խնդրում ենք ընտրել ձեր ժամային գոտին:",
        "Choosing an User Icon":"Օգտվողի պատկերակի ընտրություն",
        "Please to choose your User Icon:":"Խնդրում ենք ընտրել ձեր օգտվողի պատկերակը:"
    },
    "az_AZ": {
        "Welcome": "Xoş gəldiniz",
        "Mail": "Poçt",
        "Install programs": "Proqramları quraşdırın",
        "Background": "Fon",
        "Finish": "Bitirmək",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "ServOS-a xoş gəldiniz. Davam etmək üçün,<br>xahiş olunur \"Növbəti\" düyməsini klikləyin",
        "Cancel": "Ləğv et",
        "Next": "Növbəti",
        "Exit": "Çıxış",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Əgər e-poçtunuzu poçt müştərisinə əlavə etmək istəyirsinizsə,<br>xahiş olunur \"E-poçt əlavə et\" düyməsini klikləyin",
        "Back": "Geri",
        "Add email": "E-poçt əlavə et",
        "What's programs, which you want to install?": "Hansı proqramları quraşdırmaq istəyirsiniz?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "ServOS-un quraşdırılmasını tamamladınız.<br>\"Çıxış\" düyməsini klikləyə bilərsiniz",
        "Please to add you community region:": "Xahiş olunur icmanızın regionunu əlavə edin:",
        "Please to choose your backgroud:": "Xahiş olunur fon seçin:",
        "Weather": "Hava",
        "Add": "Əlavə et",
        "Remove": "Sil",
        "Your community": "Sizin icma",
        "Time Zone":"Saat qurşağı",
        "Please to select your timezone:":"Zəhmət olmasa saat qurşağınızı seçin:",
        "Choosing an User Icon":"İstifadəçi ikonunu seçmək",
        "Please to choose your User Icon:":"Zəhmət olmasa istifadəçi ikonunu seçin:"
    },
    "bg_BG": {
        "Welcome": "Добре дошли",
        "Mail": "Поща",
        "Install programs": "Инсталиране на програми",
        "Background": "Фон",
        "Finish": "Завърши",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Добре дошли в ServOS. За да продължите с инсталирането,<br>моля натиснете \"Напред\"",
        "Cancel": "Отказ",
        "Next": "Напред",
        "Exit": "Изход",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Ако искате да добавите своя имейл към пощенския клиент,<br>моля натиснете \"Добави имейл\"",
        "Back": "Назад",
        "Add email": "Добави имейл",
        "What's programs, which you want to install?": "Кои програми искате да инсталирате?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Завършихте инсталацията на ServOS.<br>Можете да натиснете \"Изход\"",
        "Please to add you community region:": "Моля добавете вашия регион:",
        "Please to choose your backgroud:": "Моля изберете своя фон:",
        "Weather": "Времето",
        "Add": "Добави",
        "Remove": "Премахни",
        "Your community": "Вашата общност",
        "Time Zone":"Часова зона",
        "Please to select your timezone:":"Моля, изберете вашата часова зона:",
        "Choosing an User Icon":"Избор на икона на потребителя",
        "Please to choose your User Icon:":"Моля, изберете своята икона на потребителя:"
    },
    "zh_CN": {
        "Welcome": "欢迎",
        "Mail": "邮件",
        "Install programs": "安装程序",
        "Background": "背景",
        "Finish": "完成",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "欢迎使用ServOS。要继续安装，<br>请点击“下一步”",
        "Cancel": "取消",
        "Next": "下一步",
        "Exit": "退出",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "如果您想将电子邮件添加到邮件客户端，<br>请点击“添加电子邮件”",
        "Back": "返回",
        "Add email": "添加电子邮件",
        "What's programs, which you want to install?": "您想安装哪些程序？",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "您已完成ServOS的安装。<br>您可以点击“退出”",
        "Please to add you community region:": "请添加您的社区区域：",
        "Please to choose your backgroud:": "请选择您的背景：",
        "Weather": "天气",
        "Add": "添加",
        "Remove": "移除",
        "Your community": "您的社区",
        "Time Zone":"时区",
        "Please to select your timezone:":"请选择您的时区:",
        "Choosing an User Icon":"选择用户图标",
        "Please to choose your User Icon:":"请选择您的用户图标："
    },
    "zh_TW": {
        "Welcome": "歡迎",
        "Mail": "郵件",
        "Install programs": "安裝程序",
        "Background": "背景",
        "Finish": "完成",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "歡迎使用ServOS。要繼續安裝，<br>請點擊“下一步”",
        "Cancel": "取消",
        "Next": "下一步",
        "Exit": "退出",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "如果您想將電子郵件添加到郵件客戶端，<br>請點擊“添加電子郵件”",
        "Back": "返回",
        "Add email": "添加電子郵件",
        "What's programs, which you want to install?": "您想安裝哪些程序？",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "您已完成ServOS的安裝。<br>您可以點擊“退出”",
        "Please to add you community region:": "請添加您的社區區域：",
        "Please to choose your backgroud:": "請選擇您的背景：",
        "Weather": "天氣",
        "Add": "添加",
        "Remove": "移除",
        "Your community": "您的社區",
        "Time Zone":"時區",
        "Please to select your timezone:":"請選擇您的時區:",
        "Choosing an User Icon":"選擇使用者圖示",
        "Please to choose your User Icon:":"請選擇您的使用者圖示："
    },
    "hr_HR": {
        "Welcome": "Dobrodošli",
        "Mail": "Pošta",
        "Install programs": "Instaliraj programe",
        "Background": "Pozadina",
        "Finish": "Završi",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Dobrodošli u ServOS. Za nastavak instalacije,<br>molimo kliknite \"Dalje\"",
        "Cancel": "Otkaži",
        "Next": "Dalje",
        "Exit": "Izlaz",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Ako želite dodati svoju e-poštu u klijent za poštu,<br>molimo kliknite \"Dodaj e-poštu\"",
        "Back": "Natrag",
        "Add email": "Dodaj e-poštu",
        "What's programs, which you want to install?": "Koje programe želite instalirati?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Dovršili ste instalaciju ServOS-a.<br>Možete kliknuti \"Izlaz\"",
        "Please to add you community region:": "Molimo dodajte svoju regiju zajednice:",
        "Please to choose your backgroud:": "Molimo odaberite svoju pozadinu:",
        "Weather": "Vrijeme",
        "Add": "Dodaj",
        "Remove": "Ukloni",
        "Your community": "Vaša zajednica",
        "Time Zone":"Vremenska zona",
        "Please to select your timezone:":"Molimo odaberite svoju vremensku zonu:",
        "Choosing an User Icon":"Odabir korisničke ikone",
        "Please to choose your User Icon:":"Molimo odaberite svoju korisničku ikonu:"
    },
    "cs_CZ": {
        "Welcome": "Vítejte",
        "Mail": "Pošta",
        "Install programs": "Instalovat programy",
        "Background": "Pozadí",
        "Finish": "Dokončit",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Vítejte v ServOS. Pro pokračování instalace,<br>klikněte prosím na \"Další\"",
        "Cancel": "Zrušit",
        "Next": "Další",
        "Exit": "Konec",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Pokud chcete přidat svůj e-mail do e-mailového klienta,<br>klikněte prosím na \"Přidat e-mail\"",
        "Back": "Zpět",
        "Add email": "Přidat e-mail",
        "What's programs, which you want to install?": "Jaké programy chcete nainstalovat?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Dokončili jste instalaci ServOS.<br>Můžete kliknout na \"Konec\"",
        "Please to add you community region:": "Přidejte prosím svou komunitní oblast:",
        "Please to choose your backgroud:": "Vyberte si prosím své pozadí:",
        "Weather": "Počasí",
        "Add": "Přidat",
        "Remove": "Odstranit",
        "Your community": "Vaše komunita",
        "Time Zone":"Časové pásmo",
        "Please to select your timezone:":"Vyberte prosím své časové pásmo:",
        "Choosing an User Icon":"Výběr uživatelské ikony",
        "Please to choose your User Icon:":"Vyberte prosím svou uživatelskou ikonu:"
    },
    "da_DK": {
        "Welcome": "Velkommen",
        "Mail": "Mail",
        "Install programs": "Installer programmer",
        "Background": "Baggrund",
        "Finish": "Afslut",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Velkommen til ServOS. For at fortsætte installationen,<br>klik venligst på \"Næste\"",
        "Cancel": "Annuller",
        "Next": "Næste",
        "Exit": "Afslut",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Hvis du vil tilføje din e-mail til mailklienten,<br>klik venligst på \"Tilføj e-mail\"",
        "Back": "Tilbage",
        "Add email": "Tilføj e-mail",
        "What's programs, which you want to install?": "Hvilke programmer vil du installere?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Du har fuldført installationen af ServOS.<br>Du kan klikke på \"Afslut\"",
        "Please to add you community region:": "Tilføj venligst din region:",
        "Please to choose your backgroud:": "Vælg venligst din baggrund:",
        "Weather": "Vejret",
        "Add": "Tilføj",
        "Remove": "Fjern",
        "Your community": "Dit fællesskab",
        "Time Zone":"Tidszone",
        "Please to select your timezone:":"Vælg venligst din tidszone:",
        "Choosing an User Icon":"Valg af brugerikon",
        "Please to choose your User Icon:":"Vælg venligst dit brugerikon:"
    },
    "nl_NL": {
        "Welcome": "Welkom",
        "Mail": "E-mail",
        "Install programs": "Programma's installeren",
        "Background": "Achtergrond",
        "Finish": "Voltooien",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Welkom bij ServOS. Voor voortzetting van de installatie,<br>klik op \"Volgende\"",
        "Cancel": "Annuleren",
        "Next": "Volgende",
        "Exit": "Afsluiten",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Als u uw e-mail aan de e-mailclient wilt toevoegen,<br>klik dan op \"E-mail toevoegen\"",
        "Back": "Terug",
        "Add email": "E-mail toevoegen",
        "What's programs, which you want to install?": "Welke programma's wilt u installeren?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "U heeft de installatie van ServOS voltooid.<br>U kunt op \"Afsluiten\" klikken",
        "Please to add you community region:": "Voeg uw regio toe:",
        "Please to choose your backgroud:": "Kies uw achtergrond:",
        "Weather": "Weer",
        "Add": "Toevoegen",
        "Remove": "Verwijderen",
        "Your community": "Uw gemeenschap",
        "Time Zone":"Tijdzone",
        "Please to select your timezone:":"Selecteer uw tijdzone:",
        "Choosing an User Icon":"Een gebruikerspictogram kiezen",
        "Please to choose your User Icon:":"Kies uw gebruikerspictogram:"
    },
    "en_US":{
        "Welcome":"Welcome",
        "Mail":"Mail",
        "Install programs":"Install programs",
        "Background":"Background",
        "User icon":"User icon",
        "Finish":"Finish",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"Welcome to ServOS. For continuation installing,<br>please to click \"Next\"",
        "Cancel":"Cancel",
        "Next":"Next",
        "Exit":"Exit",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"If you want to add your email to mail client,<br>please to click \"Add email\"",
        "Back":"Back",
        "Add email":"Add email",
        "What's programs, which you want to install?":"What's programs, which you want to install?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"You complete instalation ServOS.<br>You may to click \"Exit\"",
        "Please to add you community region:":"Please to add you community region:",
        "Please to choose your backgroud:":"Please to choose your backgroud:",
        "Please to choose your user icon:":"Please to choose your user icon:",
        "Weather":"Weather",
        "Add":"Add",
        "Remove":"Remove",
        "Your community":"Your community",
        "Time Zone":"Time Zone",
        "Please to select your timezone:":"Please to select your timezone:",
        "Choosing an User Icon":"Choosing an User Icon",
        "Please to choose your User Icon:":"Please to choose your User Icon:"
    },
    "en_GB":{
        "Welcome":"Welcome",
        "Mail":"Mail",
        "Install programs":"Install programs",
        "Background":"Background",
        "User icon":"User icon",
        "Finish":"Finish",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"Welcome to ServOS. For continuation installing,<br>please to click \"Next\"",
        "Cancel":"Cancel",
        "Next":"Next",
        "Exit":"Exit",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"If you want to add your email to mail client,<br>please to click \"Add email\"",
        "Back":"Back",
        "Add email":"Add email",
        "What's programs, which you want to install?":"What's programs, which you want to install?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"You complete instalation ServOS.<br>You may to click \"Exit\"",
        "Please to add you community region:":"Please to add you community region:",
        "Please to choose your backgroud:":"Please to choose your backgroud:",
        "Please to choose your user icon:":"Please to choose your user icon:",
        "Weather":"Weather",
        "Add":"Add",
        "Remove":"Remove",
        "Your community":"Your community",
        "Time Zone":"Time Zone",
        "Please to select your timezone:":"Please to select your timezone:",
        "Choosing an User Icon":"Choosing a User Icon",
        "Please to choose your User Icon:":"Please choose your User Icon:"
    },
    "en_CA":{
        "Welcome":"Welcome",
        "Mail":"Mail",
        "Install programs":"Install programs",
        "Background":"Background",
        "User icon":"User icon",
        "Finish":"Finish",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"Welcome to ServOS. For continuation installing,<br>please to click \"Next\"",
        "Cancel":"Cancel",
        "Next":"Next",
        "Exit":"Exit",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"If you want to add your email to mail client,<br>please to click \"Add email\"",
        "Back":"Back",
        "Add email":"Add email",
        "What's programs, which you want to install?":"What's programs, which you want to install?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"You complete instalation ServOS.<br>You may to click \"Exit\"",
        "Please to add you community region:":"Please to add you community region:",
        "Please to choose your backgroud:":"Please to choose your backgroud:",
        "Please to choose your user icon:":"Please to choose your user icon:",
        "Weather":"Weather",
        "Add":"Add",
        "Remove":"Remove",
        "Your community":"Your community",
        "Time Zone":"Time Zone",
        "Please to select your timezone:":"Please to select your timezone:",
        "Choosing an User Icon":"Choosing a User Icon",
        "Please to choose your User Icon:":"Please choose your User Icon:"
    },
    "en_AU":{
        "Welcome":"Welcome",
        "Mail":"Mail",
        "Install programs":"Install programs",
        "Background":"Background",
        "User icon":"User icon",
        "Finish":"Finish",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"Welcome to ServOS. For continuation installing,<br>please to click \"Next\"",
        "Cancel":"Cancel",
        "Next":"Next",
        "Exit":"Exit",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"If you want to add your email to mail client,<br>please to click \"Add email\"",
        "Back":"Back",
        "Add email":"Add email",
        "What's programs, which you want to install?":"What's programs, which you want to install?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"You complete instalation ServOS.<br>You may to click \"Exit\"",
        "Please to add you community region:":"Please to add you community region:",
        "Please to choose your backgroud:":"Please to choose your backgroud:",
        "Please to choose your user icon:":"Please to choose your user icon:",
        "Weather":"Weather",
        "Add":"Add",
        "Remove":"Remove",
        "Your community":"Your community",
        "Time Zone":"Time Zone",
        "Please to select your timezone:":"Please to select your timezone:",
        "Choosing an User Icon":"Choosing a User Icon",
        "Please to choose your User Icon:":"Please choose your User Icon:"
    },
    "et_EE": {
        "Welcome": "Tere tulemast",
        "Mail": "E-post",
        "Install programs": "Paigalda programmid",
        "Background": "Taust",
        "Finish": "Lõpeta",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Tere tulemast ServOS-i. Paigaldamise jätkamiseks,<br>klõpsake palun \"Järgmine\"",
        "Cancel": "Tühista",
        "Next": "Järgmine",
        "Exit": "Välju",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Kui soovite lisada oma e-posti meilikliendile,<br>klõpsake palun \"Lisa e-post\"",
        "Back": "Tagasi",
        "Add email": "Lisa e-post",
        "What's programs, which you want to install?": "Milliseid programme soovite paigaldada?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Olete lõpetanud ServOS-i paigaldamise.<br>Võite klõpsata \"Välju\"",
        "Please to add you community region:": "Palun lisage oma kogukonna piirkond:",
        "Please to choose your backgroud:": "Palun valige oma taust:",
        "Weather": "Ilm",
        "Add": "Lisa",
        "Remove": "Eemalda",
        "Your community": "Teie kogukond",
        "Time Zone":"Ajavöönd",
        "Please to select your timezone:":"Palun valige oma ajavöönd:",
        "Choosing an User Icon":"Kasutaja ikooni valimine",
        "Please to choose your User Icon:":"Palun valige oma kasutaja ikoon:"
    },
    "fi_FI": {
        "Welcome": "Tervetuloa",
        "Mail": "Sähköposti",
        "Install programs": "Asenna ohjelmat",
        "Background": "Tausta",
        "Finish": "Valmis",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Tervetuloa ServOS:iin. Jatkaaksesi asennusta,<br>klikkaa \"Seuraava\"",
        "Cancel": "Peruuta",
        "Next": "Seuraava",
        "Exit": "Poistu",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Jos haluat lisätä sähköpostisi sähköpostiohjelmaan,<br>klikkaa \"Lisää sähköposti\"",
        "Back": "Takaisin",
        "Add email": "Lisää sähköposti",
        "What's programs, which you want to install?": "Mitä ohjelmia haluat asentaa?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Olet suorittanut ServOS:n asennuksen.<br>Voit klikata \"Poistu\"",
        "Please to add you community region:": "Lisää yhteisösi alue:",
        "Please to choose your backgroud:": "Valitse taustasi:",
        "Weather": "Sää",
        "Add": "Lisää",
        "Remove": "Poista",
        "Your community": "Yhteisösi",
        "Time Zone":"Aikavyöhyke",
        "Please to select your timezone:":"Valitse aikavyöhyke:",
        "Choosing an User Icon":"Käyttäjäkuvakkeen valinta",
        "Please to choose your User Icon:":"Valitse käyttäjäkuvake:"
    },
    "fr_FR": {
        "Welcome": "Bienvenue",
        "Mail": "Courriel",
        "Install programs": "Installer des programmes",
        "Background": "Arrière-plan",
        "Finish": "Terminer",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Bienvenue sur ServOS. Pour continuer l'installation,<br>cliquez sur \"Suivant\"",
        "Cancel": "Annuler",
        "Next": "Suivant",
        "Exit": "Quitter",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Si vous souhaitez ajouter votre courriel au client de messagerie,<br>cliquez sur \"Ajouter un courriel\"",
        "Back": "Retour",
        "Add email": "Ajouter un courriel",
        "What's programs, which you want to install?": "Quels programmes souhaitez-vous installer ?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Vous avez terminé l'installation de ServOS.<br>Vous pouvez cliquer sur \"Quitter\"",
        "Please to add you community region:": "Veuillez ajouter votre région communautaire :",
        "Please to choose your backgroud:": "Veuillez choisir votre arrière-plan :",
        "Weather": "Météo",
        "Add": "Ajouter",
        "Remove": "Supprimer",
        "Your community": "Votre communauté",
        "Time Zone":"Fuseau horaire",
        "Please to select your timezone:":"Veuillez sélectionner votre fuseau horaire:",
        "Choosing an User Icon":"Choisir une icône d'utilisateur",
        "Please to choose your User Icon:":"Veuillez choisir votre icône d'utilisateur:"
    },
    "fr_CA": {
        "Welcome": "Bienvenue",
        "Mail": "Courriel",
        "Install programs": "Installer des programmes",
        "Background": "Arrière-plan",
        "Finish": "Terminer",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Bienvenue sur ServOS. Pour continuer l'installation,<br>cliquez sur \"Suivant\"",
        "Cancel": "Annuler",
        "Next": "Suivant",
        "Exit": "Quitter",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Si vous souhaitez ajouter votre courriel au client de messagerie,<br>cliquez sur \"Ajouter un courriel\"",
        "Back": "Retour",
        "Add email": "Ajouter un courriel",
        "What's programs, which you want to install?": "Quels programmes souhaitez-vous installer ?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Vous avez terminé l'installation de ServOS.<br>Vous pouvez cliquer sur \"Quitter\"",
        "Please to add you community region:": "Veuillez ajouter votre région communautaire :",
        "Please to choose your backgroud:": "Veuillez choisir votre arrière-plan :",
        "Weather": "Météo",
        "Add": "Ajouter",
        "Remove": "Supprimer",
        "Your community": "Votre communauté",
        "Time Zone":"Fuseau horaire",
        "Please to select your timezone:":"Veuillez choisir votre fuseau horaire:",
        "Choosing an User Icon":"Choisir une icône d'utilisateur",
        "Please to choose your User Icon:":"Veuillez choisir votre icône d'utilisateur:"
    },
    "ka_GE": {
        "Welcome": "კეთილი იყოს თქვენი მობრძანება",
        "Mail": "ფოსტა",
        "Install programs": "პროგრამების ინსტალაცია",
        "Background": "ფონი",
        "Finish": "დასრულება",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "კეთილი იყოს თქვენი მობრძანება ServOS-ში. ინსტალაციის გასაგრძელებლად,<br>გთხოვთ დააწკაპუნეთ \"შემდეგი\"",
        "Cancel": "გაუქმება",
        "Next": "შემდეგი",
        "Exit": "გასვლა",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "თუ გსურთ დაამატოთ თქვენი ელ. ფოსტა ფოსტის კლიენტს,<br>გთხოვთ დააწკაპუნეთ \"დაამატეთ ელ. ფოსტა\"",
        "Back": "უკან",
        "Add email": "დაამატეთ ელ. ფოსტა",
        "What's programs, which you want to install?": "რა პროგრამები გსურთ დააინსტალიროთ?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "თქვენ დაასრულეთ ServOS-ის ინსტალაცია.<br>შეგიძლიათ დააწკაპუნოთ \"გასვლა\"",
        "Please to add you community region:": "გთხოვთ დაამატოთ თქვენი რეგიონის თემატი:",
        "Please to choose your backgroud:": "გთხოვთ აირჩიოთ თქვენი ფონი:",
        "Weather": "ამინდი",
        "Add": "დამატება",
        "Remove": "ამოშლა",
        "Your community": "თქვენი საზოგადოება",
        "Time Zone":"დროის სარტყელი",
        "Please to select your timezone:":"გთხოვთ, აირჩიოთ თქვენი დროის სარტყელი:",
        "Choosing an User Icon":"მომხმარებლის აიკონის არჩევა",
        "Please to choose your User Icon:":"გთხოვთ, აირჩიოთ თქვენი მომხმარებლის აიკონი:"
    },
    "de_DE": {
        "Welcome": "Willkommen",
        "Mail": "E-Mail",
        "Install programs": "Programme installieren",
        "Background": "Hintergrund",
        "Finish": "Fertigstellen",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Willkommen bei ServOS. Um mit der Installation fortzufahren,<br>klicken Sie bitte auf \"Weiter\"",
        "Cancel": "Abbrechen",
        "Next": "Weiter",
        "Exit": "Beenden",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Wenn Sie Ihre E-Mail dem E-Mail-Client hinzufügen möchten,<br>klicken Sie bitte auf \"E-Mail hinzufügen\"",
        "Back": "Zurück",
        "Add email": "E-Mail hinzufügen",
        "What's programs, which you want to install?": "Welche Programme möchten Sie installieren?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Sie haben die Installation von ServOS abgeschlossen.<br>Sie können auf \"Beenden\" klicken",
        "Please to add you community region:": "Bitte fügen Sie Ihre Gemeinschaftsregion hinzu:",
        "Please to choose your backgroud:": "Bitte wählen Sie Ihren Hintergrund:",
        "Weather": "Wetter",
        "Add": "Hinzufügen",
        "Remove": "Entfernen",
        "Your community": "Ihre Gemeinschaft",
        "Time Zone":"Zeitzone",
        "Please to select your timezone:":"Bitte wählen Sie Ihre Zeitzone aus:",
        "Choosing an User Icon":"Benutzersymbol auswählen",
        "Please to choose your User Icon:":"Bitte wählen Sie Ihr Benutzersymbol:"
    },
    "el_GR": {
        "Welcome": "Καλώς ήρθατε",
        "Mail": "Ηλεκτρονικό Ταχυδρομείο",
        "Install programs": "Εγκατάσταση προγραμμάτων",
        "Background": "Φόντο",
        "Finish": "Ολοκλήρωση",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Καλώς ήρθατε στο ServOS. Για να συνεχίσετε την εγκατάσταση,<br>κάντε κλικ στο \"Επόμενο\"",
        "Cancel": "Ακύρωση",
        "Next": "Επόμενο",
        "Exit": "Έξοδος",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Αν θέλετε να προσθέσετε το email σας στον πελάτη αλληλογραφίας,<br>κάντε κλικ στο \"Προσθήκη email\"",
        "Back": "Πίσω",
        "Add email": "Προσθήκη email",
        "What's programs, which you want to install?": "Ποια προγράμματα θέλετε να εγκαταστήσετε;",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Ολοκληρώσατε την εγκατάσταση του ServOS.<br>Μπορείτε να κάνετε κλικ στο \"Έξοδος\"",
        "Please to add you community region:": "Παρακαλώ προσθέστε την περιοχή της κοινότητάς σας:",
        "Please to choose your backgroud:": "Παρακαλώ επιλέξτε το φόντο σας:",
        "Weather": "Καιρός",
        "Add": "Προσθήκη",
        "Remove": "Αφαίρεση",
        "Your community": "Η κοινότητά σας",
        "Time Zone":"Ζώνη ώρας",
        "Please to select your timezone:":"Παρακαλώ επιλέξτε τη ζώνη ώρας σας:",
        "Choosing an User Icon":"Επιλογή εικονιδίου χρήστη",
        "Please to choose your User Icon:":"Παρακαλώ επιλέξτε το εικονίδιο χρήστη σας:"
    },
    "he_IL": {
        "Welcome": "ברוך הבא",
        "Mail": "דוא\"ל",
        "Install programs": "התקן תוכניות",
        "Background": "רקע",
        "Finish": "סיום",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "ברוך הבא ל-ServOS. להמשך ההתקנה,<br>אנא לחץ על \"הבא\"",
        "Cancel": "ביטול",
        "Next": "הבא",
        "Exit": "יציאה",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "אם ברצונך להוסיף את הדוא\"ל שלך ללקוח הדואר,<br>אנא לחץ על \"הוסף דוא\"ל\"",
        "Back": "חזרה",
        "Add email": "הוסף דוא\"ל",
        "What's programs, which you want to install?": "אילו תוכניות ברצונך להתקין?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "השלמת את התקנת ServOS.<br>באפשרותך ללחוץ על \"יציאה\"",
        "Please to add you community region:": "אנא הוסף את אזור הקהילה שלך:",
        "Please to choose your backgroud:": "אנא בחר את הרקע שלך:",
        "Weather": "מזג אוויר",
        "Add": "הוסף",
        "Remove": "הסר",
        "Your community": "הקהילה שלך",
        "Time Zone":"אזור זמן",
        "Please to select your timezone:":"אנא בחר את אזור הזמן שלך:",
        "Choosing an User Icon":"בחירת סמל משתמש",
        "Please to choose your User Icon:":"אנא בחר את סמל המשתמש שלך:"
    },
    "hi_IN": {
        "Welcome": "स्वागत है",
        "Mail": "मेल",
        "Install programs": "कार्यक्रम इंस्टॉल करें",
        "Background": "पृष्ठभूमि",
        "Finish": "समाप्त",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "ServOS में आपका स्वागत है। इंस्टॉलेशन जारी रखने के लिए,<br>कृपया \"अगला\" पर क्लिक करें",
        "Cancel": "रद्द करें",
        "Next": "अगला",
        "Exit": "बाहर निकलें",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "यदि आप अपने ईमेल को मेल क्लाइंट में जोड़ना चाहते हैं,<br>कृपया \"ईमेल जोड़ें\" पर क्लिक करें",
        "Back": "वापस",
        "Add email": "ईमेल जोड़ें",
        "What's programs, which you want to install?": "आप कौन से प्रोग्राम इंस्टॉल करना चाहते हैं?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "आपने ServOS इंस्टॉलेशन पूरा कर लिया है।<br>आप \"बाहर निकलें\" पर क्लिक कर सकते हैं",
        "Please to add you community region:": "कृपया अपना समुदाय क्षेत्र जोड़ें:",
        "Please to choose your backgroud:": "कृपया अपनी पृष्ठभूमि चुनें:",
        "Weather": "मौसम",
        "Add": "जोड़ें",
        "Remove": "हटाएं",
        "Your community": "आपका समुदाय",
        "Time Zone":"समय क्षेत्र",
        "Please to select your timezone:":"कृपया अपना समय क्षेत्र चुनें:",
        "Choosing an User Icon":"उपयोगकर्ता आइकन चुनना",
        "Please to choose your User Icon:":"कृपया अपना उपयोगकर्ता आइकन चुनें:"
    },
    "hu_HU": {
        "Welcome": "Üdvözöljük",
        "Mail": "E-mail",
        "Install programs": "Programok telepítése",
        "Background": "Háttér",
        "Finish": "Befejezés",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Üdvözöljük a ServOS-ban. A telepítés folytatásához,<br>kattintson a \"Tovább\" gombra",
        "Cancel": "Mégse",
        "Next": "Tovább",
        "Exit": "Kilépés",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Ha hozzá szeretné adni e-mailjét az e-mail klienshez,<br>kattintson az \"E-mail hozzáadása\" gombra",
        "Back": "Vissza",
        "Add email": "E-mail hozzáadása",
        "What's programs, which you want to install?": "Milyen programokat szeretne telepíteni?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Befejezte a ServOS telepítését.<br>Kattinthat a \"Kilépés\" gombra",
        "Please to add you community region:": "Kérjük, adja hozzá közösségi régióját:",
        "Please to choose your backgroud:": "Kérjük, válassza ki a hátterét:",
        "Weather": "Időjárás",
        "Add": "Hozzáad",
        "Remove": "Eltávolít",
        "Your community": "Az Ön közössége",
        "Time Zone":"Időzóna",
        "Please to select your timezone:":"Kérjük, válassza ki az időzónáját:",
        "Choosing an User Icon":"Felhasználói ikon kiválasztása",
        "Please to choose your User Icon:":"Kérjük, válassza ki a felhasználói ikonját:"
    },
    "it_IT": {
        "Welcome": "Benvenuto",
        "Mail": "Posta",
        "Install programs": "Installa programmi",
        "Background": "Sfondo",
        "Finish": "Fine",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Benvenuto in ServOS. Per continuare l'installazione,<br>clicca su \"Avanti\"",
        "Cancel": "Annulla",
        "Next": "Avanti",
        "Exit": "Esci",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Se vuoi aggiungere la tua email al client di posta,<br>clicca su \"Aggiungi email\"",
        "Back": "Indietro",
        "Add email": "Aggiungi email",
        "What's programs, which you want to install?": "Quali programmi desideri installare?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Hai completato l'installazione di ServOS.<br>Puoi cliccare su \"Esci\"",
        "Please to add you community region:": "Per favore, aggiungi la tua regione di comunità:",
        "Please to choose your backgroud:": "Per favore, scegli il tuo sfondo:",
        "Weather": "Meteo",
        "Add": "Aggiungi",
        "Remove": "Rimuovi",
        "Your community": "La tua comunità",
        "Time Zone":"Fuso orario",
        "Please to select your timezone:":"Seleziona il tuo fuso orario:",
        "Choosing an User Icon":"Scelta di un'icona utente",
        "Please to choose your User Icon:":"Per favore, scegli la tua icona utente:"
    },
    "ja_JP": {
        "Welcome": "ようこそ",
        "Mail": "メール",
        "Install programs": "プログラムをインストール",
        "Background": "背景",
        "Finish": "終了",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "ServOSへようこそ。インストールを続行するには、<br>「次へ」をクリックしてください",
        "Cancel": "キャンセル",
        "Next": "次へ",
        "Exit": "終了",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "メールクライアントにメールを追加する場合は、<br>「メールを追加」をクリックしてください",
        "Back": "戻る",
        "Add email": "メールを追加",
        "What's programs, which you want to install?": "インストールしたいプログラムは何ですか？",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "ServOSのインストールが完了しました。<br>「終了」をクリックできます",
        "Please to add you community region:": "コミュニティの地域を追加してください：",
        "Please to choose your backgroud:": "背景を選択してください：",
        "Weather": "天気",
        "Add": "追加",
        "Remove": "削除",
        "Your community": "あなたのコミュニティ",
        "Time Zone":"タイムゾーン",
        "Please to select your timezone:":"タイムゾーンを選択してください:",
        "Choosing an User Icon":"ユーザーアイコンの選択",
        "Please to choose your User Icon:":"ユーザーアイコンを選択してください："
    },
    "kk_KZ": {
        "Welcome": "Қош келдіңіз",
        "Mail": "Пошта",
        "Install programs": "Бағдарламаларды орнату",
        "Background": "Фон",
        "Finish": "Аяқтау",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "ServOS-қа қош келдіңіз. Орнатуды жалғастыру үшін,<br>\"Келесі\" түймесін басыңыз",
        "Cancel": "Бас тарту",
        "Next": "Келесі",
        "Exit": "Шығу",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Егер пошта клиентіне электрондық поштаңызды қосқыңыз келсе,<br>\"Электрондық поштаны қосу\" түймесін басыңыз",
        "Back": "Артқа",
        "Add email": "Электрондық поштаны қосу",
        "What's programs, which you want to install?": "Қандай бағдарламаларды орнатқыңыз келеді?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Сіз ServOS орнатуды аяқтадыңыз.<br>\"Шығу\" түймесін баса аласыз",
        "Please to add you community region:": "Қоғамдастық аймағын қосыңыз:",
        "Please to choose your backgroud:": "Фоныңызды таңдаңыз:",
        "Weather": "Ауа райы",
        "Add": "Қосу",
        "Remove": "Жою",
        "Your community": "Сіздің қауымдастығыңыз",
        "Time Zone":"Уақыт белдеуі",
        "Please to select your timezone:":"Өз уақыт белдеуіңізді таңдаңыз:",
        "Choosing an User Icon":"Пайдаланушы белгішесін таңдау",
        "Please to choose your User Icon:":"Пайдаланушы белгішесін таңдаңыз:"
    },
    "ko_KR": {
        "Welcome": "환영합니다",
        "Mail": "메일",
        "Install programs": "프로그램 설치",
        "Background": "배경",
        "Finish": "완료",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "ServOS에 오신 것을 환영합니다. 설치를 계속하려면,<br>\"다음\"을 클릭하십시오",
        "Cancel": "취소",
        "Next": "다음",
        "Exit": "종료",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "메일 클라이언트에 이메일을 추가하려면,<br>\"이메일 추가\"를 클릭하십시오",
        "Back": "뒤로",
        "Add email": "이메일 추가",
        "What's programs, which you want to install?": "어떤 프로그램을 설치하고 싶습니까?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "ServOS 설치를 완료했습니다.<br>\"종료\"를 클릭할 수 있습니다",
        "Please to add you community region:": "커뮤니티 지역을 추가하십시오:",
        "Please to choose your backgroud:": "배경을 선택하십시오:",
        "Weather": "날씨",
        "Add": "추가",
        "Remove": "제거",
        "Your community": "당신의 커뮤니티",
        "Time Zone":"시간대",
        "Please to select your timezone:":"시간대를 선택하세요:",
        "Choosing an User Icon":"사용자 아이콘 선택",
        "Please to choose your User Icon:":"사용자 아이콘을 선택하십시오:"
    },
    "ky_KG": {
        "Welcome": "Кош келдиңиз",
        "Mail": "Почта",
        "Install programs": "Программаларды орнотуу",
        "Background": "Фон",
        "Finish": "Бүттү",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "ServOSке кош келиңиз. Орнотууну улантуу үчүн,<br>\"Кийинки\" баскычын басыңыз",
        "Cancel": "Жокко чыгаруу",
        "Next": "Кийинки",
        "Exit": "Чыгуу",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Эгерде почта кардарына почтаңызды кошкуңуз келсе,<br>\"Почтаны кошуу\" баскычын басыңыз",
        "Back": "Артка",
        "Add email": "Почтаны кошуу",
        "What's programs, which you want to install?": "Кайсы программаларды орноткуңуз келет?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Сиз ServOS орнотууну бүтүрдүңүз.<br>\"Чыгуу\" баскычын бассаңыз болот",
        "Please to add you community region:": "Сураныч, жамааттык аймакты кошуңуз:",
        "Please to choose your backgroud:": "Фонуңузду тандаңыз:",
        "Weather": "Аба ырайы",
        "Add": "Кошуу",
        "Remove": "Алуу",
        "Your community": "Сиздин жамаатыңыз",
        "Time Zone":"Саат алкагы",
        "Please to select your timezone:":"Өзүңүздүн саат алкагыңызды тандаңыз:",
        "Choosing an User Icon":"Колдонуучунун белгисин тандоо",
        "Please to choose your User Icon:":"Колдонуучунун белгисин тандаңыз:"
    },
    "lv_LV": {
        "Welcome": "Laipni lūdzam",
        "Mail": "Pasts",
        "Install programs": "Instalēt programmas",
        "Background": "Fons",
        "Finish": "Pabeigts",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Laipni lūdzam ServOS. Lai turpinātu instalēšanu,<br>lūdzu, noklikšķiniet uz \"Nākamais\"",
        "Cancel": "Atcelt",
        "Next": "Nākamais",
        "Exit": "Iziet",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Ja vēlaties pievienot savu e-pastu pasta klientam,<br>lūdzu, noklikšķiniet uz \"Pievienot e-pastu\"",
        "Back": "Atpakaļ",
        "Add email": "Pievienot e-pastu",
        "What's programs, which you want to install?": "Kādas programmas jūs vēlaties instalēt?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Jūs esat pabeidzis ServOS instalēšanu.<br>Jūs varat noklikšķināt uz \"Iziet\"",
        "Please to add you community region:": "Lūdzu, pievienojiet savu kopienas reģionu:",
        "Please to choose your backgroud:": "Lūdzu, izvēlieties savu fona attēlu:",
        "Weather": "Laiks",
        "Add": "Pievienot",
        "Remove": "Noņemt",
        "Your community": "Jūsu kopiena",
        "Time Zone":"Laika zona",
        "Please to select your timezone:":"Lūdzu, izvēlieties savu laika joslu:",
        "Choosing an User Icon":"Lietotāja ikonas izvēle",
        "Please to choose your User Icon:":"Lūdzu, izvēlieties savu lietotāja ikonu:"
    },
    "lt_LT": {
        "Welcome": "Sveiki atvykę",
        "Mail": "Paštas",
        "Install programs": "Įdiegti programą",
        "Background": "Fonas",
        "Finish": "Baigti",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Sveiki atvykę į ServOS. Norėdami tęsti diegimą,<br>prašome spustelėti „Toliau“",
        "Cancel": "Atšaukti",
        "Next": "Toliau",
        "Exit": "Išeiti",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Jei norite pridėti savo el. pašto adresą pašto klientui,<br>prašome spustelėti „Pridėti el. paštą“",
        "Back": "Atgal",
        "Add email": "Pridėti el. paštą",
        "What's programs, which you want to install?": "Kokias programas norite įdiegti?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Jūs baigėte ServOS diegimą.<br>Galite spustelėti „Išeiti“",
        "Please to add you community region:": "Prašome pridėti savo bendruomenės regioną:",
        "Please to choose your backgroud:": "Prašome pasirinkti savo fono paveikslėlį:",
        "Weather": "Orai",
        "Add": "Pridėti",
        "Remove": "Pašalinti",
        "Your community": "Jūsų bendruomenė",
        "Time Zone":"Laiko juosta",
        "Please to select your timezone:":"Prašome pasirinkti savo laiko juostą:",
        "Choosing an User Icon":"Vartotojo piktogramos pasirinkimas",
        "Please to choose your User Icon:":"Prašome pasirinkti savo vartotojo piktogramą:"
    },
    "mn_MN": {
        "Welcome": "Тавтай морил",
        "Mail": "Захидал",
        "Install programs": "Програм суулгах",
        "Background": "Дэвсгэр",
        "Finish": "Дуусгах",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Тавтай морилно уу ServOS. Суулганыг үргэлжлүүлэхийн тулд,<br>зааварчилж буй \"Дараагийн\" товчлуураа дарна уу",
        "Cancel": "Цуцлах",
        "Next": "Дараагийн",
        "Exit": "Гарах",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Та өөрийн и-мэйл хаягийг шуудангийн үйлчлэгчид нэмж өгөхийг хүсвэл,<br>\"И-мэйл нэмэх\" товчлуураа дарна уу",
        "Back": "Буцах",
        "Add email": "И-мэйл нэмэх",
        "What's programs, which you want to install?": "Та ямар програм суулгахыг хүсч байна уу?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Та ServOS-г суулгасан байна.<br>\"Гарах\" товчлуураа дарж чадах болно",
        "Please to add you community region:": "Та өөрийн хамтран амьдралын бүсийг нэмж өгнө үү:",
        "Please to choose your backgroud:": "Та өөрийн дэвсгэрийг сонгоно уу:",
        "Weather": "Цаг агаар",
        "Add": "Нэмэх",
        "Remove": "Хасах",
        "Your community": "Таны байгууллага",
        "Time Zone":"Цагийн бүс",
        "Please to select your timezone:":"Өөрийн цагийн бүсээ сонгоно уу:",
        "Choosing an User Icon":"Хэрэглэгчийн дүрс сонгох",
        "Please to choose your User Icon:":"Өөрийн хэрэглэгчийн дүрсээ сонгоно уу:"
    },
    "fa_IR": {
        "Welcome": "خوش آمدید",
        "Mail": "ایمیل",
        "Install programs": "نصب برنامه‌ها",
        "Background": "پس زمینه",
        "Finish": "پایان",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "خوش آمدید به ServOS. برای ادامه نصب،<br>لطفاً بر روی \"بعدی\" کلیک کنید",
        "Cancel": "لغو",
        "Next": "بعدی",
        "Exit": "خروج",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "اگر می خواهید ایمیل خود را به مشتری پستی اضافه کنید،<br>لطفاً بر روی \"افزودن ایمیل\" کلیک کنید",
        "Back": "بازگشت",
        "Add email": "افزودن ایمیل",
        "What's programs, which you want to install?": "برنامه‌هایی که می‌خواهید نصب کنید چیست؟",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "نصب ServOS را تکمیل کرده‌اید.<br>می‌توانید بر روی \"خروج\" کلیک کنید",
        "Please to add you community region:": "لطفاً منطقه جامعه خود را اضافه کنید:",
        "Please to choose your backgroud:": "لطفاً پس زمینه خود را انتخاب کنید:",
        "Weather": "آب و هوا",
        "Add": "افزودن",
        "Remove": "حذف",
        "Your community": "جامعه شما",
        "Time Zone":"منطقه زمانی",
        "Please to select your timezone:":"لطفاً منطقه زمانی خود را انتخاب کنید:",
        "Choosing an User Icon":"انتخاب نماد کاربر",
        "Please to choose your User Icon:":"لطفاً نماد کاربر خود را انتخاب کنید:"
    },
    "pl_PL": {
        "Welcome": "Witaj",
        "Mail": "Poczta",
        "Install programs": "Zainstaluj programy",
        "Background": "Tło",
        "Finish": "Zakończ",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Witaj w ServOS. Aby kontynuować instalację,<br>proszę kliknąć „Dalej“",
        "Cancel": "Anuluj",
        "Next": "Dalej",
        "Exit": "Wyjdź",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Jeśli chcesz dodać swój adres e-mail do klienta poczty,<br>proszę kliknąć „Dodaj e-mail“",
        "Back": "Wstecz",
        "Add email": "Dodaj e-mail",
        "What's programs, which you want to install?": "Jakie programy chcesz zainstalować?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Zakończyłeś instalację ServOS.<br>Możesz kliknąć „Wyjdź“",
        "Please to add you community region:": "Proszę dodać region społeczności:",
        "Please to choose your backgroud:": "Proszę wybrać tło:",
        "Weather": "Pogoda",
        "Add": "Dodaj",
        "Remove": "Usuń",
        "Your community": "Twoja społeczność",
        "Time Zone":"Strefa czasowa",
        "Please to select your timezone:":"Wybierz swoją strefę czasową:",
        "Choosing an User Icon":"Wybór ikony użytkownika",
        "Please to choose your User Icon:":"Proszę wybrać swoją ikonę użytkownika:"
    },
    "pt_PT": {
        "Welcome": "Bem-vindo",
        "Mail": "Correio",
        "Install programs": "Instalar programas",
        "Background": "Fundo",
        "Finish": "Terminar",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Bem-vindo ao ServOS. Para continuar a instalação,<br>por favor clique em \"Seguinte\"",
        "Cancel": "Cancelar",
        "Next": "Seguinte",
        "Exit": "Sair",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Se quiser adicionar o seu email ao cliente de correio,<br>por favor clique em \"Adicionar email\"",
        "Back": "Voltar",
        "Add email": "Adicionar email",
        "What's programs, which you want to install?": "Quais programas deseja instalar?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Concluiu a instalação do ServOS.<br>Pode clicar em \"Sair\"",
        "Please to add you community region:": "Por favor, adicione a região da sua comunidade:",
        "Please to choose your backgroud:": "Por favor, escolha o seu fundo:",
        "Weather": "Tempo",
        "Add": "Adicionar",
        "Remove": "Remover",
        "Your community": "Sua comunidade",
        "Time Zone":"Fuso horário",
        "Please to select your timezone:":"Por favor, selecione seu fuso horário:",
        "Choosing an User Icon":"Escolha de um ícone de utilizador",
        "Please to choose your User Icon:":"Por favor, escolha o seu ícone de utilizador:"
    },
    "pt_BR": {
        "Welcome": "Bem-vindo",
        "Mail": "Correio",
        "Install programs": "Instalar programas",
        "Background": "Fundo",
        "Finish": "Terminar",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Bem-vindo ao ServOS. Para continuar a instalação,<br>por favor clique em \"Próximo\"",
        "Cancel": "Cancelar",
        "Next": "Próximo",
        "Exit": "Sair",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Se deseja adicionar seu e-mail ao cliente de e-mail,<br>por favor clique em \"Adicionar e-mail\"",
        "Back": "Voltar",
        "Add email": "Adicionar e-mail",
        "What's programs, which you want to install?": "Quais programas você deseja instalar?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Você concluiu a instalação do ServOS.<br>Você pode clicar em \"Sair\"",
        "Please to add you community region:": "Por favor, adicione a região da sua comunidade:",
        "Please to choose your backgroud:": "Por favor, escolha o seu fundo:",
        "Weather": "Tempo",
        "Add": "Adicionar",
        "Remove": "Remover",
        "Your community": "Sua comunidade",
        "Time Zone":"Fuso horário",
        "Please to select your timezone:":"Por favor, selecione seu fuso horário:",
        "Choosing an User Icon":"Escolha de um ícone de usuário",
        "Please to choose your User Icon:":"Por favor, escolha o seu ícone de usuário:"
    },
    "ro_RO": {
        "Welcome": "Bine ai venit",
        "Mail": "Poștă",
        "Install programs": "Instalare programe",
        "Background": "Fundal",
        "Finish": "Finalizare",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Bine ai venit la ServOS. Pentru a continua instalarea,<br>vă rugăm să faceți clic pe „Următorul“",
        "Cancel": "Anulare",
        "Next": "Următorul",
        "Exit": "Ieșire",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Dacă doriți să adăugați adresa dvs. de email la clientul de email,<br>vă rugăm să faceți clic pe „Adăugați email“",
        "Back": "Înapoi",
        "Add email": "Adăugați email",
        "What's programs, which you want to install?": "Ce programe doriți să instalați?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Ați finalizat instalarea ServOS.<br>Puteți face clic pe „Ieșire“",
        "Please to add you community region:": "Vă rugăm să adăugați regiunea comunității dvs.:",
        "Please to choose your backgroud:": "Vă rugăm să alegeți fundalul dvs.:",
        "Weather": "Vremea",
        "Add": "Adăugați",
        "Remove": "Eliminați",
        "Your community": "Comunitatea ta",
        "Time Zone":"Fus orar",
        "Please to select your timezone:":"Vă rugăm să selectați fusul orar:",
        "Choosing an User Icon":"Alegerea unei pictograme de utilizator",
        "Please to choose your User Icon:":"Vă rugăm să alegeți pictograma utilizatorului:"
    },
    "ru_RU": {
        "Welcome": "Добро пожаловать",
        "Mail": "Почта",
        "Install programs": "Установить программы",
        "Background": "Фон",
        "Finish": "Завершить",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Добро пожаловать в ServOS. Для продолжения установки,<br>пожалуйста, нажмите \"Далее\"",
        "Cancel": "Отмена",
        "Next": "Далее",
        "Exit": "Выход",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Если вы хотите добавить свой электронный адрес в почтовый клиент,<br>пожалуйста, нажмите \"Добавить электронную почту\"",
        "Back": "Назад",
        "Add email": "Добавить электронную почту",
        "What's programs, which you want to install?": "Какие программы вы хотите установить?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Вы завершили установку ServOS.<br>Вы можете нажать \"Выход\"",
        "Please to add you community region:": "Пожалуйста, добавьте регион вашего сообщества:",
        "Please to choose your backgroud:": "Пожалуйста, выберите ваш фон:",
        "Weather": "Погода",
        "Add": "Добавить",
        "Remove": "Удалить",
        "Your community": "Ваш населённый пункт",
        "Time Zone":"Часовой пояс",
        "Please to select your timezone:":"Выберите ваш часовой пояс:",
        "Choosing an User Icon":"Выбор значка пользователя",
        "Please to choose your User Icon:":"Пожалуйста, выберите значок пользователя:"
    },
    "sr_RS": {
        "Welcome": "Добродошли",
        "Mail": "Пошта",
        "Install programs": "Инсталирај програме",
        "Background": "Позадина",
        "Finish": "Заврши",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Добродошли на ServOS. За наставак инсталације,<br>молимо кликните на „Даље“",
        "Cancel": "Откажи",
        "Next": "Даље",
        "Exit": "Излаз",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Ако желите да додате своју е-пошту клијенту за е-пошту,<br>молимо кликните на „Додај е-пошту“",
        "Back": "Назад",
        "Add email": "Додај е-пошту",
        "What's programs, which you want to install?": "Које програме желите да инсталирате?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Завршили сте инсталацију ServOS-а.<br>Можете кликнути на „Излаз“",
        "Please to add you community region:": "Молимо вас да додате регион ваше заједнице:",
        "Please to choose your backgroud:": "Молимо вас да изаберете своју позадину:",
        "Weather": "Време",
        "Add": "Додај",
        "Remove": "Уклони",
        "Your community": "Ваша заједница",
        "Time Zone":"Временска зона",
        "Please to select your timezone:":"Молимо одаберите вашу временску зону:",
        "Choosing an User Icon":"Избор иконе корисника",
        "Please to choose your User Icon:":"Молимо вас да изаберете икону корисника:"
    },
    "sr_RS_latin": {
        "Welcome": "Dobrodošli",
        "Mail": "Pošta",
        "Install programs": "Instaliraj programe",
        "Background": "Pozadina",
        "Finish": "Završi",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Dobrodošli na ServOS. Za nastavak instalacije,<br>molimo kliknite na „Dalje“",
        "Cancel": "Otkaži",
        "Next": "Dalje",
        "Exit": "Izlaz",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Ako želite da dodate svoju e-poštu klijentu za e-poštu,<br>molimo kliknite na „Dodaj e-poštu“",
        "Back": "Nazad",
        "Add email": "Dodaj e-poštu",
        "What's programs, which you want to install?": "Koje programe želite da instalirate?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Završili ste instalaciju ServOS-a.<br>Možete kliknuti na „Izlaz“",
        "Please to add you community region:": "Molimo vas da dodate region vaše zajednice:",
        "Please to choose your backgroud:": "Molimo vas da izaberete svoju pozadinu:",
        "Weather": "Vreme",
        "Add": "Dodaj",
        "Remove": "Ukloni",
        "Your community": "Vaša zajednica",
        "Time Zone":"Vremenska zona",
        "Please to select your timezone:":"Molimo odaberite vašu vremensku zonu:",
        "Choosing an User Icon":"Izbor ikone korisnika",
        "Please to choose your User Icon:":"Molimo vas da izaberete ikonu korisnika:"
    },
    "sk_SK": {
        "Welcome": "Vitajte",
        "Mail": "Pošta",
        "Install programs": "Inštalovať programy",
        "Background": "Pozadie",
        "Finish": "Dokončiť",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Vitajte v ServOS-e. Pre pokračovanie inštalácie,<br>prosím kliknite na „Ďalej“",
        "Cancel": "Zrušiť",
        "Next": "Ďalej",
        "Exit": "Ukončiť",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Ak chcete pridať svoj e-mail do poštového klienta,<br>prosím kliknite na „Pridať e-mail“",
        "Back": "Späť",
        "Add email": "Pridať e-mail",
        "What's programs, which you want to install?": "Ktoré programy chcete nainštalovať?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Dokončili ste inštaláciu ServOS.<br>Môžete kliknúť na „Ukončiť“",
        "Please to add you community region:": "Prosím, pridajte región vašej komunity:",
        "Please to choose your backgroud:": "Prosím, vyberte svoje pozadie:",
        "Weather": "Počasie",
        "Add": "Pridať",
        "Remove": "Odstrániť",
        "Your community": "Vaša komunita",
        "Time Zone":"Časové pásmo",
        "Please to select your timezone:":"Vyberte si svoje časové pásmo:",
        "Choosing an User Icon":"Výber ikony používateľa",
        "Please to choose your User Icon:":"Prosím, vyberte si ikonu používateľa:"
    },
    "sl_SI": {
        "Welcome": "Dobrodošli",
        "Mail": "E-pošta",
        "Install programs": "Namesti programe",
        "Background": "Ozadje",
        "Finish": "Končaj",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Dobrodošli v ServOS. Za nadaljevanje namestitve,<br>prosim kliknite na „Naprej“",
        "Cancel": "Prekliči",
        "Next": "Naprej",
        "Exit": "Izhod",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Če želite dodati svoj e-poštni naslov v e-poštni odjemalec,<br>prosim kliknite na „Dodaj e-pošto“",
        "Back": "Nazaj",
        "Add email": "Dodaj e-pošto",
        "What's programs, which you want to install?": "Katere programe želite namestiti?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Končali ste namestitev ServOS-a.<br>Lahko kliknete na „Izhod“",
        "Please to add you community region:": "Prosimo, dodajte regijo vaše skupnosti:",
        "Please to choose your backgroud:": "Prosimo, izberite svoje ozadje:",
        "Weather": "Vreme",
        "Add": "Dodaj",
        "Remove": "Odstrani",
        "Your community": "Vaša skupnost",
        "Time Zone":"Časovni pas",
        "Please to select your timezone:":"Izberite svoj časovni pas:",
        "Choosing an User Icon":"Izbira uporabniške ikone",
        "Please to choose your User Icon:":"Prosimo, izberite svojo uporabniško ikono:"
    },
    "es_ES": {
        "Welcome": "Bienvenido",
        "Mail": "Correo",
        "Install programs": "Instalar programas",
        "Background": "Fondo",
        "Finish": "Finalizar",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Bienvenido a ServOS. Para continuar con la instalación,<br>por favor haga clic en \"Siguiente\"",
        "Cancel": "Cancelar",
        "Next": "Siguiente",
        "Exit": "Salir",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Si desea agregar su correo electrónico al cliente de correo,<br>por favor haga clic en \"Agregar correo electrónico\"",
        "Back": "Atrás",
        "Add email": "Agregar correo electrónico",
        "What's programs, which you want to install?": "¿Qué programas desea instalar?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Ha completado la instalación de ServOS.<br>Puede hacer clic en \"Salir\"",
        "Please to add you community region:": "Por favor, añada la región de su comunidad:",
        "Please to choose your backgroud:": "Por favor, elija su fondo:",
        "Weather": "Tiempo",
        "Add": "Agregar",
        "Remove": "Eliminar",
        "Your community": "Tu comunidad",
        "Time Zone":"Zona horaria",
        "Please to select your timezone:":"Por favor, seleccione su zona horaria:",
        "Choosing an User Icon":"Elegir un icono de usuario",
        "Please to choose your User Icon:":"Por favor, elija su icono de usuario:"
    },
    "sv_SE": {
        "Welcome": "Välkommen",
        "Mail": "E-post",
        "Install programs": "Installera program",
        "Background": "Bakgrund",
        "Finish": "Avsluta",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "Välkommen till ServOS. För att fortsätta installationen,<br>vänligen klicka på \"Nästa\"",
        "Cancel": "Avbryt",
        "Next": "Nästa",
        "Exit": "Avsluta",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "Om du vill lägga till din e-post till e-postklienten,<br>vänligen klicka på \"Lägg till e-post\"",
        "Back": "Tillbaka",
        "Add email": "Lägg till e-post",
        "What's programs, which you want to install?": "Vilka program vill du installera?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "Du har slutfört installationen av ServOS.<br>Du kan klicka på \"Avsluta\"",
        "Please to add you community region:": "Vänligen lägg till din gemenskapsregion:",
        "Please to choose your backgroud:": "Vänligen välj din bakgrund:",
        "Weather": "Väder",
        "Add": "Lägg till",
        "Remove": "Ta bort",
        "Your community": "Din gemenskap",
        "Time Zone":"Tidszon",
        "Please to select your timezone:":"Välj din tidszon:",
        "Choosing an User Icon":"Välj en användarikon",
        "Please to choose your User Icon:":"Vänligen välj din användarikon:"
    },
    "tt_RU":{
        "Welcome":"Рәхим итегез",
        "Mail":"Почта",
        "Install programs":"Программалар урнаштыру",
        "Background":"Фон",
        "User icon":"Кулланучы иконасы",
        "Finish":"Тәмамлау",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"ServOSка рәхим итегез. Установканы дәвам итү өчен,<br>\"Алга\" төймәсенә басыгыз",
        "Cancel":"Юкка чыгару",
        "Next":"Алга",
        "Exit":"Чыгу",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"Әгәр дә сез үзегезнең электрон почтагызны почта клиентына өстәүне теләсәгез,<br>\"Электрон почта өстәү\" төймәсенә басыгыз",
        "Back":"Артка",
        "Add email":"Электрон почта өстәү",
        "What's programs, which you want to install?":"Нинди программалар урнаштырырга телисез?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"ServOS урнаштыру тәмам.<br>Сез \"Чыгу\" төймәсенә баса аласыз",
        "Please to add you community region:":"Зинһар, үзегезнең төбәкне өстәгез:",
        "Please to choose your backgroud:":"Зинһар, фон сайлагыз:",
        "Please to choose your user icon:":"Зинһар, кулланучы иконасын сайлагыз:",
        "Weather":"Һава торышы",
        "Add":"Өстәү",
        "Remove":"Бетерү",
        "Your community":"Сезнең җәмгыять",
        "Time Zone":"Вакыт зонасы",
        "Please to select your timezone:":"Зинһар, үзегезнең вакыт зонасын сайлагыз:",
        "Choosing an User Icon":"Кулланучы билгесен сайлау",
        "Please to choose your User Icon:":"Зинһар, кулланучы билгесен сайлагыз:"
    },
    "th_TH":{
        "Welcome":"ยินดีต้อนรับ",
        "Mail":"จดหมาย",
        "Install programs":"ติดตั้งโปรแกรม",
        "Background":"พื้นหลัง",
        "User icon":"ไอคอนผู้ใช้",
        "Finish":"เสร็จสิ้น",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"ยินดีต้อนรับสู่ ServOS หากต้องการดำเนินการติดตั้งต่อ<br>โปรดคลิก \"ถัดไป\"",
        "Cancel":"ยกเลิก",
        "Next":"ถัดไป",
        "Exit":"ออก",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"หากคุณต้องการเพิ่มอีเมลของคุณลงในไคลเอ็นต์อีเมล<br>โปรดคลิก \"เพิ่มอีเมล\"",
        "Back":"กลับ",
        "Add email":"เพิ่มอีเมล",
        "What's programs, which you want to install?":"โปรแกรมที่คุณต้องการติดตั้งคืออะไร?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"คุณเสร็จสิ้นการติดตั้ง ServOS<br>คุณสามารถคลิก \"ออก\"",
        "Please to add you community region:":"กรุณาเพิ่มภูมิภาคของชุมชนของคุณ:",
        "Please to choose your backgroud:":"กรุณาเลือกพื้นหลังของคุณ:",
        "Please to choose your user icon:":"กรุณาเลือกไอคอนผู้ใช้ของคุณ:",
        "Weather":"สภาพอากาศ",
        "Add":"เพิ่ม",
        "Remove":"ลบ",
        "Your community":"ชุมชนของคุณ",
        "Time Zone":"เขตเวลา",
        "Please to select your timezone:":"กรุณาเลือกเขตเวลาของคุณ:",
        "Choosing an User Icon":"การเลือกไอคอนผู้ใช้",
        "Please to choose your User Icon:":"โปรดเลือกไอคอนผู้ใช้ของคุณ:"
    },
    "bo_CN": {
        "Welcome": "བཀའ་འགྱུར",
        "Mail": "སྐད་དུ།",
        "Install programs": "གསར་ཤོས་ཚུ་ཐོབ་ཡོད།",
        "Background": "གསར་མ།",
        "User icon": "ལག་ཐོག་ཀྱི་སོང་བའི་ནང་གི་རེའུ།",
        "Finish": "མཇུག་ཁོ།",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"": "ServOS གི་འཆར་ལོག་ཡུན་བསྐྱོད་པའི་གསར་ཤོས་ནང་ཡོད། <br>\"Next\" འཐོམ་པ་ཡིན།",
        "Cancel": "མཉམ།",
        "Next": "བྱེད།",
        "Exit": "ཕྱིར་འཕྱེ།",
        "If you want to add your email to mail client,<br>please to click \"Add email\"": "ཁྱེད་ཀྱིས་དྲན་དེབ་དྲི་མའི་ཁག་འདོགས་ནང་ཡོད་པའི་མཐེབ་གཞན་<br>\"Add email\" འཐོམ་པ་ཡིན།",
        "Back": "རྒྱབ།",
        "Add email": "དྲན་དེབ་ཡིག་ཆ་ཡོད།",
        "What's programs, which you want to install?": "གསར་ཤོས་ཚུ་ཐོབ་ཡོད་མི་ཆོག",
        "You complete instalation ServOS.<br>You may to click \"Exit\"": "ServOS གི་གསར་ཤོས་དང་ཁ་སྐོང་གི་བསམ་གཏན་ཡོད།<br>\"Exit\" འཐོམ་པ་ཡིན།",
        "Please to add you community region:": "ཁྱེད་ཀྱིས་གནས་ཚད་ཁ་ཕྱིར།",
        "Please to choose your backgroud:": "ཁྱེད་ཀྱིས་གསར་མ་སོང་བའི་མཐེབ་གཞན་ཕྱིར།",
        "Please to choose your user icon:": "ཁྱེད་ཀྱིས་ལག་ཐོག་ཀྱི་སོང་བའི་རེའུ་ཕྱིར།",
        "Weather": "ལྷག་གི་སྒུག།",
        "Add": "ཡིག་ཆ།",
        "Remove": "ཆ་སྣོད།",
        "Your community": "ཁྱེད་ཀྱིས་གནས་ཚད།",
        "Time Zone":"དུས་ཚད་སྒྲིག་ཡུལ།",
        "Please to select your timezone:":"ཁྱེད་ཀྱི་དུས་ཚད་སྒྲིག་ཡུལ་བདག་གཟིགས།:",
        "Choosing an User Icon":"བཀོད་པའི་སྤྱོད་མཁན་རིས",
        "Please to choose your User Icon:":"ཁྱེད་ཀྱི་སྤྱོད་མཁན་རིས་གདམ་རོགས་གནང་།:"
    },
    "tr_TR":{
        "Welcome":"Hoş geldiniz",
        "Mail":"Posta",
        "Install programs":"Programları yükle",
        "Background":"Arka plan",
        "User icon":"Kullanıcı simgesi",
        "Finish":"Bitir",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"ServOS'a hoş geldiniz. Kurulumu devam ettirmek için,<br>\"İleri\"'ye tıklayınız",
        "Cancel":"İptal",
        "Next":"İleri",
        "Exit":"Çıkış",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"E-postanızı posta istemcinize eklemek istiyorsanız,<br>\"E-posta ekle\"'ye tıklayınız",
        "Back":"Geri",
        "Add email":"E-posta ekle",
        "What's programs, which you want to install?":"Hangi programları yüklemek istiyorsunuz?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"ServOS kurulumunu tamamladınız.<br>\"Çıkış\"'a tıklayabilirsiniz",
        "Please to add you community region:":"Topluluk bölgenizi ekleyin:",
        "Please to choose your backgroud:":"Arka planınızı seçin:",
        "Please to choose your user icon:":"Kullanıcı simgenizi seçin:",
        "Weather":"Hava durumu",
        "Add":"Ekle",
        "Remove":"Kaldır",
        "Your community":"Topluluğunuz",
        "Time Zone":"Saat Dilimi",
        "Please to select your timezone:":"Lütfen saat diliminizi seçin:",
        "Choosing an User Icon":"Kullanıcı simgesini seçme",
        "Please to choose your User Icon:":"Lütfen kullanıcı simgenizi seçin:"
    },
    "tk_TM":{
        "Welcome":"Hoş geldiniz",
        "Mail":"Posta",
        "Install programs":"Programlary ýükle",
        "Background":"Arka plan",
        "User icon":"Ulanyjy nyşany",
        "Finish":"Tamamla",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"ServOS'a hoş geldiniz. Yüklemeye devam etmek için,<br>\"Ileri\"'ye basyň",
        "Cancel":"Birakmak",
        "Next":"Ileri",
        "Exit":"Çyk",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"Eger siz e-mailiňizi poçta ulgamyndaky görkezmegiňize goşmak isleýärsiňiz bolsa,ň<be>E-mail goş\" düwmäsinde basyň",
        "Back":"Arka",
        "Add email":"E-mail goş",
        "What's programs, which you want to install?":"Siz ýükleýän programlaryňyzyň ady näme?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"Siz ServOS'u ulanmaga ýetirdiňiz.<br>\"Çyk\" düwmäsinde basyp aýrylalaň",
        "Please to add you community region:":"Siziň jamgyr bolanyňyzyn ýerini goşuň",
        "Please to choose your backgroud:":"Arka planyňyzy saýlaň",
        "Please to choose your user icon:":"Ulanyjy nyşanyňyzy saýlaň",
        "Weather":"Howa şertleri",
        "Add":"Goş",
        "Remove":"Aýyryň",
        "Your community":"Siziň jamgyr bolanyňyz",
        "Time Zone":"Sagat guşagy",
        "Please to select your timezone:":"Sagat guşagyňyzy saýlaň:",
        "Choosing an User Icon":"Ulanyjy nyşanyny saýlamak",
        "Please to choose your User Icon:":"Öz ulanyjy nyşanyňyzy saýlaň:"
    },
    "uk_UA":{
        "Welcome":"Ласкаво просимо",
        "Mail":"Пошта",
        "Install programs":"Встановлення програм",
        "Background":"Фон",
        "User icon":"Іконка користувача",
        "Finish":"Завершити",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"Ласкаво просимо до ServOS. Для продовження встановлення,<br>натисніть «Далі»",
        "Cancel":"Скасувати",
        "Next":"Далі",
        "Exit":"Вихід",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"Якщо ви хочете додати свою електронну пошту до поштового клієнта,<br>натисніть «Додати електронну пошту»",
        "Back":"Назад",
        "Add email":"Додати електронну пошту",
        "What's programs, which you want to install?":"Які програми ви хочете встановити?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"Ви завершили встановлення ServOS.<br>Ви можете натиснути «Вихід»",
        "Please to add you community region:":"Будь ласка, додайте ваш регіон спільноти:",
        "Please to choose your backgroud:":"Будь ласка, виберіть свій фон:",
        "Please to choose your user icon:":"Будь ласка, виберіть свою іконку користувача:",
        "Weather":"Погода",
        "Add":"Додати",
        "Remove":"Видалити",
        "Your community":"Ваша місцева громада",
        "Time Zone":"Часовий пояс",
        "Please to select your timezone:":"Оберіть ваш часовий пояс:",
        "Choosing an User Icon":"Вибір значка користувача",
        "Please to choose your User Icon:":"Будь ласка, виберіть свій значок користувача:"
    },
    "ur_PK":{
        "Welcome":"خوش آمدید",
        "Mail":"میل",
        "Install programs":"پروگرامز انسٹال کریں",
        "Background":"پس منظر",
        "User icon":"صارف آئیکن",
        "Finish":"ختم کریں",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"خوش آمدید سرو او ایس میں۔ جاری رکھنے کیلئے انسٹال کرنے کے لئے، <br>براہ کرم \"اگلا\" پر کلک کریں۔",
        "Cancel":"منسوخ کریں",
        "Next":"اگلا",
        "Exit":"باہر نکلیں",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"اگر آپ اپنا ای میل میل کلائنٹ میں شامل کرنا چاہتے ہیں، <br>تو براہ کرم \"ای میل شامل کریں\" پر کلک کریں۔",
        "Back":"پیچھے",
        "Add email":"ای میل شامل کریں",
        "What's programs, which you want to install?":"آپ کون سے پروگرام انسٹال کرنا چاہتے ہیں؟",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"آپ نے سرو او ایس کی انسٹالیشن مکمل کر لی ہے۔ <br>آپ \"باہر نکلیں\" پر کلک کرسکتے ہیں۔",
        "Please to add you community region:":"براہ کرم اپنا کمیونٹی ریجن شامل کریں:",
        "Please to choose your backgroud:":"براہ کرم اپنا پس منظر منتخب کریں:",
        "Please to choose your user icon:":"براہ کرم اپنا صارف آئیکن منتخب کریں:",
        "Weather":"موسم",
        "Add":"شامل کریں",
        "Remove":"ہٹائیں",
        "Your community":"آپ کی کمیونٹی",
        "Time Zone":"ٹائم زون",
        "Please to select your timezone:":"براہ کرم اپنا ٹائم زون منتخب کریں:",
        "Choosing an User Icon":"صارف کا آئیکن منتخب کریں",
        "Please to choose your User Icon:":"براہ کرم اپنا صارف آئیکن منتخب کریں:"
    },
    "ug_CN":{
        "Welcome":"خۇش كەلدىڭىز",
        "Mail":"مېل",
        "Install programs":"ئەپلەرنى ئىنساللاڭ",
        "Background":"ئارقا پىسىق",
        "User icon":"ئىشلەتكۈچى ئىكونى",
        "Finish":"تامام",
        "Welcome to ServOS. For continuation installing,<br>please to click \"Next\"":"ServOSغا قاراڭلىق كېلەرسىز. داۋاملىق ئىنساللاش ئۈچۈن \"كىيىنكى\" نى چاپلاڭ.",
        "Cancel":"بىكار قىل",
        "Next":"كىيىنكى",
        "Exit":"چىكىنىش",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"ئېلخەت ئادرېسىڭىزنى ئېلخەت تورىغا قوشۇشقا بولغاندا \"ئېلخەت قوش\" نى چاپلاڭ.",
        "Back":"ئارقىغا",
        "Add email":"ئېلخەت قوش",
        "What's programs, which you want to install?":"قانداق پروگرامما ئىنسال قىلماقچىسىز؟",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"ServOSنى ئىنساللىشنى ئۆتكۈردىڭىز.<br>«چىكىنىش» نى چاپلايسىز",
        "Please to add you community region:":"كومۇنىتېتىڭىزنىڭ ئوبلاستىنى قوشۇڭ:",
        "Please to choose your backgroud:":"ئارقا پىسىقتىڭىزنى تاللاڭ:",
        "Please to choose your user icon:":"ئىشلەتكۈچى ئىكونىڭىزنى تاللاڭ:",
        "Weather":"ئېغىرلىق",
        "Add":"قوش",
        "Remove":"چىقىرىۋەت",
        "Your community":"سىزنىڭ كومۇنىتېتىڭىز",
        "Time Zone":"ۋاقىت رايونى",
        "Please to select your timezone:":"سۆزلىتىش ۋاقتى رايونىڭىزنى تاللاڭ:",
        "Choosing an User Icon":"ئىشلەتكۈچى سىنبەلگىسىنى تاللاش",
        "Please to choose your User Icon:":"ئىشلەتكۈچى سىنبەلگىڭىزنى تاللاڭ:"
    },
    "uz_UZ":{
        "Welcome":"Xush kelibsiz",
        "Mail":"Pochta",
        "Install programs":"Dasturlarni o'rnatish",
        "Background":"Orqa fon",
        "User icon":"Foydalanuvchi belgisi",
        "Finish":"Tugatish",
        "Welcome to ServOS. Davom etish uchun, iltimos, \"Keyingisi\" tugmasini bosing":"ServOSga xush kelibsiz. Davom etish uchun, iltimos, \"Keyingisi\" tugmasini bosing",
        "Cancel":"Bekor qilish",
        "Next":"Keyingisi",
        "Exit":"Chiqish",
        "If you want to add your email to mail client, iltimos, \"Pochta qo'shish\" tugmasini bosing":"Agar pochtangizni pochta mijoziga qo'shmoqchi bo'lsangiz, iltimos, \"Pochta qo'shish\" tugmasini bosing",
        "Back":"Orqaga",
        "Add email":"Pochta qo'shish",
        "What's programs, which you want to install?":"O'rnatmoqchi bo'lgan dasturlar qaysilarni?",
        "You complete instalation ServOS. Chiqish tugmasini bosing":"ServOS o'rnatilishini tugatdingiz. Chiqish tugmasini bosing",
        "Please to add you community region:":"Ijtimoiy hududingizni qo'shing:",
        "Please to choose your backgroud:":"Orqa fonni tanlang:",
        "Please to choose your user icon:":"Foydalanuvchi belgisini tanlang:",
        "Weather":"Ob-havo",
        "Add":"Qo'shish",
        "Remove":"Olib tashlash",
        "Your community":"Sizning jamiyat",
        "Time Zone":"Vaqt zonasi",
        "Please to select your timezone:":"Iltimos, vaqt zonasini tanlang:",
        "Choosing an User Icon":"Foydalanuvchi belgisini tanlash",
        "Please to choose your User Icon:":"Iltimos, foydalanuvchi belgisini tanlang:"
    },
    "vi_VN":{
        "Welcome":"Chào mừng",
        "Mail":"Thư",
        "Install programs":"Cài đặt chương trình",
        "Background":"Nền",
        "User icon":"Biểu tượng người dùng",
        "Finish":"Hoàn thành",
        "Welcome to ServOS. Để tiếp tục cài đặt,<br>vui lòng nhấn \"Tiếp theo\"":"Chào mừng đến với ServOS. Để tiếp tục cài đặt,<br>vui lòng nhấn \"Tiếp theo\"",
        "Cancel":"Hủy bỏ",
        "Next":"Tiếp theo",
        "Exit":"Thoát",
        "If you want to add your email to mail client,<br>please to click \"Add email\"":"Nếu bạn muốn thêm email của mình vào client thư,<br>vui lòng nhấn \"Thêm email\"",
        "Back":"Quay lại",
        "Add email":"Thêm email",
        "What's programs, which you want to install?":"Các chương trình bạn muốn cài đặt là gì?",
        "You complete instalation ServOS.<br>You may to click \"Exit\"":"Bạn đã hoàn thành cài đặt ServOS.<br>Bạn có thể nhấn \"Thoát\"",
        "Please to add you community region:":"Vui lòng thêm khu vực cộng đồng của bạn:",
        "Please to choose your backgroud:":"Vui lòng chọn nền của bạn:",
        "Please to choose your user icon:":"Vui lòng chọn biểu tượng người dùng của bạn:",
        "Weather":"Thời tiết",
        "Add":"Thêm",
        "Remove":"Xóa",
        "Your community":"Cộng đồng của bạn",
        "Time Zone":"Múi giờ",
        "Please to select your timezone:":"Vui lòng chọn múi giờ của bạn:",
        "Choosing an User Icon":"Chọn biểu tượng người dùng",
        "Please to choose your User Icon:":"Vui lòng chọn biểu tượng người dùng của bạn:"
    }
}
